[package]
name = "charisma"
version = "0.1.0"
edition = "2021"

[dependencies]
biome_css_parser = "0.5.7"
biome_css_syntax = "0.5.7"
rocket = { version = "0.5.1", features = ["json"] }
sha1 = "0.10.6"
