export const ALL_PROPERTIES = {
  "accent-color": ["auto", "color", "initial", "inherit"],
  "align-content": [
    "stretch",
    "center",
    "flex-start",
    "flex-end",
    "space-between",
    "space-around",
    "space-evenly",
    "initial",
    "inherit",
  ],
  "align-items": [
    "normal",
    "stretch",
    "center",
    "flex-start",
    "flex-end",
    "start",
    "end",
    "baseline",
    "initial",
    "inherit",
  ],
  "align-self": [
    "auto",
    "stretch",
    "center",
    "flex-start",
    "flex-end",
    "baseline",
    "initial",
    "inherit",
  ],
  all: ["initial", "inherit", "unset"],
  animation: [
    // TODO: we have to map complex values to helpers
    "animation-name",
    "animation-duration",
    "animation-timing-function",
    "animation-delay",
    "animation-iteration-count",
    "animation-direction",
    "animation-fill-mode",
    "animation-play-state",
    "initial",
    "inherit",
  ],
  "animation-delay": ["time", "initial", "inherit"],
  "animation-direction": [
    "normal",
    "reverse",
    "alternate",
    "alternate-reverse",
    "initial",
    "inherit",
  ],
  "animation-duration": ["time", "initial", "inherit"],
  "animation-fill-mode": [
    "none",
    "forwards",
    "backwards",
    "both",
    "initial",
    "inherit",
  ],
  "animation-iteration-count": ["number", "infinite", "initial", "inherit"],
  "animation-name": ["keyframename", "none", "initial", "inherit"],
  "animation-play-state": ["paused", "running", "initial", "inherit"],
  "animation-timing-function": [
    "linear",
    "ease",
    "ease-in",
    "ease-out",
    "ease-in-out",
    "step-start",
    "step-end",
    "steps(int,start|end)",
    "cubic-bezier(n,n,n,n)",
    "initial",
    "inherit",
  ],
  "aspect-ratio": ["number", "number", "initial", "inherit"],
  "backdrop-filter": ["none", "filter", "initial", "inherit"],
  "backface-visibility": ["visible", "hidden", "initial", "inherit"],
  background: [
    "background-color",
    "background-image",
    "background-position",
    "background-size",
    "background-repeat",
    "background-origin",
    "background-clip",
    "background-attachment",
    "initial",
    "inherit",
  ],
  "background-attachment": ["scroll", "fixed", "local", "initial", "inherit"],
  "background-blend-mode": [
    "normal",
    "multiply",
    "screen",
    "overlay",
    "darken",
    "lighten",
    "color-dodge",
    "saturation",
    "color",
    "luminosity",
  ],
  "background-clip": [
    "border-box",
    "padding-box",
    "content-box",
    "initial",
    "inherit",
  ],
  "background-color": ["color", "transparent", "initial", "inherit"],
  "background-image": [
    "url('URL')",
    "none",
    "conic-gradient()",
    "linear-gradient()",
    "radial-gradient()",
    "repeating-conic-gradient()",
    "repeating-linear-gradient()",
    "repeating-radial-gradient()",
    "initial",
    "inherit",
  ],
  "background-origin": [
    "padding-box",
    "border-box",
    "content-box",
    "initial",
    "inherit",
  ],
  "background-position": [
    "left top",
    "left center",
    "left bottom",
    "right top",
    "right center",
    "right bottom",
    "center top",
    "center center",
    "center bottom",
    "x% y%",
    "xpos ypos",
    "initial",
    "inherit",
  ],
  "background-position-x": [
    "left",
    "right",
    "center",
    "x%",
    "xpos",
    "xpos offset",
    "initial",
    "inherit",
  ],
  "background-position-y": [
    "top",
    "bottom",
    "center",
    "y%",
    "ypos",
    "ypos offset",
    "initial",
    "inherit",
  ],
  "background-repeat": [
    "repeat",
    "repeat-x",
    "repeat-y",
    "no-repeat",
    "space",
    "round",
    "initial",
    "inherit",
  ],
  "background-size": [
    "auto",
    "length",
    "percentage",
    "cover",
    "contain",
    "initial",
    "inherit",
  ],
  "block-size": ["auto", "length", "%", "initial", "inherit"],
  border: [
    "border-width",
    "border-style",
    "border-color",
    "initial",
    "inherit",
  ],
  "border-block": [
    "border-block-width",
    "border-block-style",
    "border-block-color",
    "initial",
    "inherit",
  ],
  "border-block-color": ["color", "transparent", "initial", "inherit"],
  "border-block-end": [
    "border-block-end-width",
    "border-block-end-style",
    "border-block-end-color",
    "initial",
    "inherit",
  ],
  "border-block-end-color": ["color", "transparent", "initial", "inherit"],
  "border-block-end-style": [
    "none",
    "hidden",
    "dotted",
    "dashed",
    "solid",
    "double",
    "groove",
    "rigde",
    "inset",
    "outset",
    "initial",
    "inherit",
  ],
  "border-block-end-width": [
    "medium",
    "thin",
    "thick",
    "length",
    "initial",
    "inherit",
  ],
  "border-block-start": [
    "border-block-start-width",
    "border-block-start-style",
    "border-block-start-color",
    "initial",
    "inherit",
  ],
  "border-block-start-color": ["color", "transparent", "initial", "inherit"],
  "border-block-start-style": [
    "none",
    "hidden",
    "dotted",
    "dashed",
    "solid",
    "double",
    "groove",
    "rigde",
    "inset",
    "outset",
    "initial",
    "inherit",
  ],
  "border-block-start-width": [
    "medium",
    "thin",
    "thick",
    "length",
    "initial",
    "inherit",
  ],
  "border-block-style": [
    "none",
    "hidden",
    "dotted",
    "dashed",
    "solid",
    "double",
    "groove",
    "rigde",
    "inset",
    "outset",
    "initial",
    "inherit",
  ],
  "border-block-width": [
    "medium",
    "thin",
    "thick",
    "length",
    "initial",
    "inherit",
  ],
  "border-bottom": [
    "border-bottom-width",
    "border-bottom-style",
    "border-bottom-color",
    "initial",
    "inherit",
  ],
  "border-bottom-color": ["color", "transparent", "initial", "inherit"],
  "border-bottom-left-radius": ["length", "%", "initial", "inherit"],
  "border-bottom-right-radius": ["length", "%", "initial", "inherit"],
  "border-bottom-style": [
    "none",
    "hidden",
    "dotted",
    "dashed",
    "solid",
    "double",
    "groove",
    "ridge",
    "inset",
    "outset",
    "initial",
    "inherit",
  ],
  "border-bottom-width": [
    "medium",
    "thin",
    "thick",
    "length",
    "initial",
    "inherit",
  ],
  "border-collapse": ["separate", "collapse", "initial", "inherit"],
  "border-color": ["color", "transparent", "initial", "inherit"],
  "border-end-end-radius": ["0", "length", "%", "initial", "inherit"],
  "border-end-start-radius": ["0", "length", "%", "initial", "inherit"],
  "border-image": [
    "border-image-source",
    "border-image-slice",
    "border-image-width",
    "border-image-outset",
    "border-image-repeat",
    "initial",
    "inherit",
  ],
  "border-image-outset": ["length", "number", "initial", "inherit"],
  "border-image-repeat": [
    "stretch",
    "repeat",
    "round",
    "space",
    "initial",
    "inherit",
  ],
  "border-image-slice": ["number", "%", "fill", "initial", "inherit"],
  "border-image-source": ["none", "image", "initial", "inherit"],
  "border-image-width": ["length", "number", "%", "auto", "initial", "inherit"],
  "border-inline": [
    "border-inline-width",
    "border-inline-style",
    "border-inline-color",
    "initial",
    "inherit",
  ],
  "border-inline-color": ["color", "transparent", "initial", "inherit"],
  "border-inline-end": [
    "border-inline-end-width",
    "border-inline-end-style",
    "border-inline-end-color",
    "initial",
    "inherit",
  ],
  "border-inline-end-color": ["color", "transparent", "initial", "inherit"],
  "border-inline-end-style": [
    "none",
    "hidden",
    "dotted",
    "dashed",
    "solid",
    "double",
    "groove",
    "rigde",
    "inset",
    "outset",
    "initial",
    "inherit",
  ],
  "border-inline-end-width": [
    "medium",
    "thin",
    "thick",
    "length",
    "initial",
    "inherit",
  ],
  "border-inline-start": [
    "border-inline-start-width",
    "border-inline-start-style",
    "border-inline-start-color",
    "initial",
    "inherit",
  ],
  "border-inline-start-color": ["color", "transparent", "initial", "inherit"],
  "border-inline-start-style": [
    "none",
    "hidden",
    "dotted",
    "dashed",
    "solid",
    "double",
    "groove",
    "rigde",
    "inset",
    "outset",
    "initial",
    "inherit",
  ],
  "border-inline-start-width": [
    "medium",
    "thin",
    "thick",
    "length",
    "initial",
    "inherit",
  ],
  "border-inline-style": [
    "none",
    "hidden",
    "dotted",
    "dashed",
    "solid",
    "double",
    "groove",
    "rigde",
    "inset",
    "outset",
    "initial",
    "inherit",
  ],
  "border-inline-width": [
    "medium",
    "thin",
    "thick",
    "length",
    "initial",
    "inherit",
  ],
  "border-left": [
    "border-left-width",
    "border-left-style",
    "border-left-color",
    "initial",
    "inherit",
  ],
  "border-left-color": ["color", "transparent", "initial", "inherit"],
  "border-left-style": [
    "none",
    "hidden",
    "dotted",
    "dashed",
    "solid",
    "double",
    "groove",
    "ridge",
    "inset",
    "outset",
    "initial",
    "inherit",
  ],
  "border-left-width": [
    "medium",
    "thin",
    "thick",
    "length",
    "initial",
    "inherit",
  ],
  "border-radius": ["length", "%", "initial", "inherit"],
  "border-right": [
    "border-right-width",
    "border-right-style",
    "border-right-color",
    "initial",
    "inherit",
  ],
  "border-right-color": ["color", "transparent", "initial", "inherit"],
  "border-right-style": [
    "none",
    "hidden",
    "dotted",
    "dashed",
    "solid",
    "double",
    "groove",
    "ridge",
    "inset",
    "outset",
    "initial",
    "inherit",
  ],
  "border-right-width": [
    "medium",
    "thin",
    "thick",
    "length",
    "initial",
    "inherit",
  ],
  "border-spacing": ["length length", "initial", "inherit"],
  "border-start-end-radius": ["0", "length", "%", "initial", "inherit"],
  "border-start-start-radius": ["0", "length", "%", "initial", "inherit"],
  "border-style": [
    "none",
    "hidden",
    "dotted",
    "dashed",
    "solid",
    "double",
    "groove",
    "ridge",
    "inset",
    "outset",
    "initial",
    "inherit",
  ],
  "border-top": [
    "border-top-width",
    "border-top-style",
    "border-top-color",
    "initial",
    "inherit",
  ],
  "border-top-color": ["color", "transparent", "initial", "inherit"],
  "border-top-left-radius": ["length", "%", "initial", "inherit"],
  "border-top-right-radius": ["length", "%", "initial", "inherit"],
  "border-top-style": [
    "none",
    "hidden",
    "dotted",
    "dashed",
    "solid",
    "double",
    "groove",
    "ridge",
    "inset",
    "outset",
    "initial",
    "inherit",
  ],
  "border-top-width": [
    "medium",
    "thin",
    "thick",
    "length",
    "initial",
    "inherit",
  ],
  "border-width": ["medium", "thin", "thick", "length", "initial", "inherit"],
  bottom: ["auto", "length", "%", "initial", "inherit"],
  "box-decoration-break": ["slice", "clone", "initial", "inherit"],
  "box-reflect": [
    "none",
    "below",
    "above",
    "left",
    "right",
    "position offset",
    "position offset gradient",
    "initial",
    "inherit",
  ],
  "box-shadow": [
    "none",
    "h-offset",
    "v-offset",
    "blur",
    "spread",
    "color",
    "inset",
    "initial",
    "inherit",
  ],
  "box-sizing": ["content-box", "border-box", "initial", "inherit"],
  "break-after": [
    "auto",
    "all",
    "always",
    "avoid",
    "avoid-column",
    "avoid-page",
    "avoid-region",
    "column",
    "left",
    "page",
    "recto",
    "region",
    "right",
    "verso",
    "initial",
    "inherit",
  ],
  "break-before": [
    "auto",
    "all",
    "always",
    "avoid",
    "avoid-column",
    "avoid-page",
    "avoid-region",
    "column",
    "left",
    "page",
    "recto",
    "region",
    "right",
    "verso",
    "initial",
    "inherit",
  ],
  "break-inside": [
    "auto",
    "avoid",
    "avoid-column",
    "avoid-page",
    "avoid-region",
    "initial",
    "inherit",
  ],
  "caption-side": ["top", "bottom", "initial", "inherit"],
  "caret-color": ["auto", "color", "initial", "inherit"],
  "@charset": ["charset"],
  clear: ["none", "left", "right", "both", "initial", "inherit"],
  clip: ["auto", "shape", "initial", "inherit"],
  "clip-path": [
    "clip-source",
    "basic-shape",
    "margin-box",
    "border-box",
    "padding-box",
    "content-box",
    "fill-box",
    "stroke-box",
    "view-box",
    "none",
    "initial",
    "inherit",
  ],
  color: ["color", "initial", "inherit"],
  "column-count": ["number", "auto", "initial", "inherit"],
  "column-fill": ["balance", "auto", "initial", "inherit"],
  "column-gap": ["length", "normal", "initial", "inherit"],
  "column-rule": [
    "column-rule-width",
    "column-rule-style",
    "column-rule-color",
    "initial",
    "inherit",
  ],
  "column-rule-color": ["color", "initial", "inherit"],
  "column-rule-style": [
    "none",
    "hidden",
    "dotted",
    "dashed",
    "solid",
    "double",
    "groove",
    "ridge",
    "inset",
    "outset",
    "initial",
    "inherit",
  ],
  "column-rule-width": [
    "medium",
    "thin",
    "thick",
    "length",
    "initial",
    "inherit",
  ],
  "column-span": ["none", "all", "initial", "inherit"],
  "column-width": ["auto", "length", "initial", "inherit"],
  columns: ["auto", "column-width", "column-count", "initial", "inherit"],
  content: [
    "normal",
    "none",
    "counter",
    "attr(attribute)",
    "string",
    "open-quote",
    "close-quote",
    "no-open-quote",
    "no-close-quote",
    "url(url)",
    "initial",
    "inherit",
  ],
  "counter-increment": ["none", "id number", "initial", "inherit"],
  "counter-reset": ["none", "id number", "initial", "inherit"],
  "counter-set": ["none", "counter-name number", "initial", "inherit"],
  cursor: [
    "alias",
    "all-scroll",
    "auto",
    "cell",
    "col-resize",
    "context-menu",
    "copy",
    "crosshair",
    "default",
    "e-resize",
    "ew-resize",
    "grab",
    "grabbing",
    "help",
    "move",
    "n-resize",
    "ne-resize",
    "nesw-resize",
    "ns-resize",
    "nw-resize",
    "nwse-resize",
    "no-drop",
    "none",
    "not-allowed",
    "pointer",
    "progress",
    "row-resize",
    "s-resize",
    "se-resize",
    "sw-resize",
    "text",
    "URL",
    "vertical-text",
    "w-resize",
    "wait",
    "zoom-in",
    "zoom-out",
    "initial",
    "inherit",
  ],
  direction: ["ltr", "rtl", "initial", "inherit"],
  display: [
    "inline",
    "block",
    "contents",
    "flex",
    "grid",
    "inline-block",
    "inline-flex",
    "inline-grid",
    "inline-table",
    "list-item",
    "run-in",
    "table",
    "table-caption",
    "table-column-group",
    "table-header-group",
    "table-footer-group",
    "table-row-group",
    "table-cell",
    "table-column",
    "table-row",
    "none",
    "initial",
    "inherit",
  ],
  "empty-cells": ["show", "hide", "initial", "inherit"],
  filter: [
    "none",
    "blur(px)",
    "brightness(%)",
    "contrast(%)",
    "drop-shadow(h-shadow v-shadow blur spread color)",
    "grayscale(%)",
    "hue-rotate(deg)",
    "invert(%)",
    "opacity(%)",
    "saturate(%)",
    "sepia(%)",
    "url()",
    "initial",
    "inherit",
  ],
  flex: [
    "flex-grow",
    "flex-shrink",
    "flex-basis",
    "auto",
    "initial",
    "none",
    "inherit",
  ],
  "flex-basis": ["number", "auto", "initial", "inherit"],
  "flex-direction": [
    "row",
    "row-reverse",
    "column",
    "column-reverse",
    "initial",
    "inherit",
  ],
  "flex-flow": ["flex-direction", "flex-wrap", "initial", "inherit"],
  "flex-grow": ["number", "initial", "inherit"],
  "flex-shrink": ["number", "initial", "inherit"],
  "flex-wrap": ["nowrap", "wrap", "wrap-reverse", "initial", "inherit"],
  float: ["none", "left", "right", "initial", "inherit"],
  font: [
    "font-style",
    "font-variant",
    "font-weight",
    "font-size/line-height",
    "font-family",
    "caption",
    "icon",
    "menu",
    "message-box",
    "small-caption",
    "status-bar",
    "initial",
    "inherit",
  ],
  "@font-face": [
    "font-family",
    "src",
    "font-stretch",
    "font-style",
    "font-weight",
    "unicode-range",
  ],
  "font-family": ["family-name / generic-family", "initial", "inherit"],
  "font-feature-settings": ["normal", "feature-value"],
  "font-kerning": ["auto", "normal", "none"],
  "font-size": [
    "medium",
    "xx-small",
    "x-small",
    "small",
    "large",
    "x-large",
    "xx-large",
    "smaller",
    "larger",
    "length",
    "%",
    "initial",
    "inherit",
  ],
  "font-size-adjust": ["number", "none", "initial", "inherit"],
  "font-stretch": [
    "ultra-condensed",
    "extra-condensed",
    "condensed",
    "semi-condensed",
    "normal",
    "semi-expanded",
    "expanded",
    "extra-expanded",
    "ultra-expanded",
    "initial",
    "inherit",
  ],
  "font-style": ["normal", "italic", "oblique", "initial", "inherit"],
  "font-variant": ["normal", "small-caps", "initial", "inherit"],
  "font-variant-caps": [
    "normal",
    "small-caps",
    "all-small-caps",
    "petite-caps",
    "all-petite-caps",
    "unicase",
    "titling-caps",
    "initial",
    "inherit",
    "unset",
  ],
  "font-weight": [
    "normal",
    "bold",
    "bolder",
    "lighter",
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
    "initial",
    "inherit",
  ],
  gap: ["row-gap", "column-gap", "initial", "inherit"],
  grid: [
    "none",
    "grid-template-rows / grid-template-columns",
    "grid-template-areas",
    "grid-template-rows / grid-auto-columns",
    "grid-auto-rows / grid-template-columns",
    "grid-template-rows / grid-auto-flow grid-auto-columns",
    "grid-auto-flow grid-auto-rows / grid-template-columns",
    "initial",
    "inherit",
  ],
  "grid-area": [
    "grid-row-start",
    "grid-column-start",
    "grid-row-end",
    "grid-column-end",
    "itemname",
  ],
  "grid-auto-columns": [
    "auto",
    "fit-content()",
    "max-content",
    "min-content",
    "minmax(min.max)",
    "length",
    "%",
  ],
  "grid-auto-flow": ["row", "column", "dense", "row dense", "column dense"],
  "grid-auto-rows": ["auto", "max-content", "min-content", "length"],
  "grid-column": ["grid-column-start", "grid-column-end"],
  "grid-column-end": ["auto", "span n", "column-line"],
  "grid-column-gap": ["length"],
  "grid-column-start": ["auto", "span n", "column-line"],
  "grid-gap": ["grid-row-gap", "grid-column-gap"],
  "grid-row": ["grid-row-start", "grid-row-end"],
  "grid-row-end": ["auto", "span n", "row-line"],
  "grid-row-gap": ["length"],
  "grid-row-start": ["auto", "row-line"],
  "grid-template": [
    "none",
    "grid-template rows / grid-template-columns",
    "grid-template-areas",
    "initial",
    "inherit",
  ],
  "grid-template-areas": ["none", "itemnames"],
  "grid-template-columns": [
    "none",
    "auto",
    "max-content",
    "min-content",
    "length",
    "initial",
    "inherit",
  ],
  "grid-template-rows": [
    "none",
    "auto",
    "max-content",
    "min-content",
    "length",
  ],
  "hanging-punctuation": [
    "none",
    "first",
    "last",
    "allow-end",
    "force-end",
    "initial",
    "inherit",
  ],
  height: ["auto", "length", "%", "initial", "inherit"],
  hyphens: ["none", "manual", "auto", "initial", "inherit"],
  "hypenate-character": ["auto", "string", "initial", "inherit"],
  "image-rendering": [
    "auto",
    "smooth",
    "high-quality",
    "crisp-edges",
    "pixelated",
    "initial",
    "inherit",
  ],
  "@import": ["url|string", "list-of-mediaqueries"],
  "inline-size": ["auto", "length", "%", "initial", "inherit"],
  inset: ["auto", "length", "%", "initial", "inherit"],
  "inset-block": ["auto", "length", "%", "initial", "inherit"],
  "inset-block-end": ["auto", "length", "%", "initial", "inherit"],
  "inset-block-start": ["auto", "length", "%", "initial", "inherit"],
  "inset-inline": ["auto", "length", "%", "initial", "inherit"],
  "inset-inline-end": ["auto", "length", "%", "initial", "inherit"],
  "inset-inline-start": ["auto", "length", "%", "initial", "inherit"],
  isolation: ["auto", "isolate", "initial", "inherit"],
  "justify-content": [
    "flex-start",
    "flex-end",
    "center",
    "space-between",
    "space-around",
    "space-evenly",
    "initial",
    "inherit",
  ],
  "justify-items": [
    "legacy",
    "normal",
    "stretch",
    "start",
    "left",
    "center",
    "end",
    "right",
    "overflow-alignment",
    "baseline alignment",
    "initial",
    "inherit",
  ],
  "justify-self": [
    "auto",
    "normal",
    "stretch",
    "start",
    "left",
    "center",
    "end",
    "right",
    "overflow-alignment",
    "baseline alignment",
    "initial",
    "inherit",
  ],
  "@keyframes": ["animationname", "keyframes-selector", "css-styles"],
  left: ["auto", "length", "%", "initial", "inherit"],
  "letter-spacing": ["normal", "length", "initial", "inherit"],
  "line-height": ["normal", "number", "length", "%", "initial", "inherit"],
  "list-style": [
    "list-style-type",
    "list-style-position",
    "list-style-image",
    "initial",
    "inherit",
  ],
  "list-style-image": ["none", "url", "initial", "inherit"],
  "list-style-position": ["inside", "outside", "initial", "inherit"],
  "list-style-type": [
    "disc",
    "armenian",
    "circle",
    "cjk-ideographic",
    "decimal",
    "decimal-leading-zero",
    "georgian",
    "hebrew",
    "hiragana",
    "hiragana-iroha",
    "katakana",
    "katakana-iroha",
    "lower-alpha",
    "lower-greek",
    "lower-latin",
    "lower-roman",
    "none",
    "square",
    "upper-alpha",
    "upper-greek",
    "upper-latin",
    "upper-roman",
    "initial",
    "inherit",
  ],
  margin: ["length", "%", "auto", "initial", "inherit"],
  "margin-block": ["auto", "length", "%", "initial", "inherit"],
  "margin-block-end": ["auto", "length", "%", "initial", "inherit"],
  "margin-block-start": ["auto", "length", "%", "initial", "inherit"],
  "margin-bottom": ["length", "%", "auto", "initial", "inherit"],
  "margin-inline": ["auto", "length", "%", "initial", "inherit"],
  "margin-inline-end": ["auto", "length", "%", "initial", "inherit"],
  "margin-inline-start": ["auto", "length", "%", "initial", "inherit"],
  "margin-left": ["length", "%", "auto", "initial", "inherit"],
  "margin-right": ["length", "%", "auto", "initial", "inherit"],
  "margin-top": ["length", "%", "auto", "initial", "inherit"],
  "mask-image": ["none", "image", "url", "initial", "inherit"],
  "mask-mode": ["match-source", "luminance", "alpha", "initial", "inherit"],
  "mask-origin": [
    "border-box",
    "content-box",
    "padding-box",
    "margin-box",
    "fill-box",
    "stroke-box",
    "view-box",
    "initial",
    "inherit",
  ],
  "mask-position": [
    "left top\n      left center\n      left bottom\n      right top\n      right center\n      right bottom\n      center top\n      center center\n      center bottom",
    "x% y%",
    "xpos ypos",
    "initial",
    "inherit",
  ],
  "mask-repeat": [
    "repeat",
    "repeat-x",
    "repeat-y",
    "space",
    "round",
    "no-repeat",
    "initial",
    "inherit",
  ],
  "mask-size": ["auto", "size", "contain", "cover", "initial", "inherit"],
  "max-height": ["none", "length", "%", "initial", "inherit"],
  "max-width": ["none", "length", "%", "initial", "inherit"],
  "@media": [],
  "max-block-size": ["auto", "length", "%", "initial", "inherit"],
  "max-inline-size": ["auto", "length", "%", "initial", "inherit"],
  "min-block-size": ["auto", "length", "%", "initial", "inherit"],
  "min-inline-size": ["auto", "length", "%", "initial", "inherit"],
  "min-height": ["length", "%", "initial", "inherit"],
  "min-width": ["length", "%", "initial", "inherit"],
  "mix-blend-mode": [
    "normal",
    "multiply",
    "screen",
    "overlay",
    "darken",
    "lighten",
    "color-dodge",
    "color-burn",
    "difference",
    "exclusion",
    "hue",
    "saturation",
    "color",
    "luminosity",
  ],
  "object-fit": [
    "fill",
    "contain",
    "cover",
    "none",
    "scale-down",
    "initial",
    "inherit",
  ],
  "object-position": ["position", "initial", "inherit"],
  offset: [
    "auto",
    "offset-anchor",
    "offset-distance",
    "offset-path",
    "offset-rotate",
    "initial",
    "inherit",
  ],
  "offset-anchor": [
    "auto",
    "left top\n      left center\n      left bottom\n      right top\n      right center\n      right bottom\n      center top\n      center center\n      center bottom",
    "xpos ypos",
    "x% y%",
    "initial",
    "inherit",
  ],
  "offset-distance": ["0", "length", "%", "initial", "inherit"],
  "offset-path": [
    "none",
    "path()",
    "ray()",
    "url()",
    "<basic-shape>",
    "initial",
    "inherit",
  ],
  "offset-rotate": [
    "auto",
    "<angle>",
    "auto <angle>",
    "reverse",
    "initial",
    "inherit",
  ],
  opacity: ["number", "initial", "inherit"],
  order: ["number", "initial", "inherit"],
  orphans: ["integer", "initial", "inherit"],
  outline: [
    "outline-width",
    "outline-style",
    "outline-color",
    "initial",
    "inherit",
  ],
  "outline-color": ["color", "initial", "inherit"],
  "outline-offset": ["length", "initial", "inherit"],
  "outline-style": [
    "none",
    "hidden",
    "dotted",
    "dashed",
    "solid",
    "double",
    "groove",
    "ridge",
    "inset",
    "outset",
    "initial",
    "inherit",
  ],
  "outline-width": ["medium", "thin", "thick", "length", "initial", "inherit"],
  overflow: [
    "visible",
    "hidden",
    "clip",
    "scroll",
    "auto",
    "initial",
    "inherit",
  ],
  "overflow-anchor": ["auto", "none", "initial", "inherit"],
  "overflow-wrap": ["normal", "anywhere", "break-word", "initial", "inherit"],
  "overflow-x": ["visible", "hidden", "scroll", "auto", "initial", "inherit"],
  "overflow-y": ["visible", "hidden", "scroll", "auto", "initial", "inherit"],
  "overscroll-behavior": ["auto", "contain", "none", "initial", "inherit"],
  "overscroll-behavior-block": [
    "auto",
    "contain",
    "none",
    "initial",
    "inherit",
  ],
  "overscroll-behavior-inline": [
    "auto",
    "contain",
    "none",
    "initial",
    "inherit",
  ],
  "overscroll-behavior-x": ["auto", "contain", "none", "initial", "inherit"],
  "overscroll-behavior-y": ["auto", "contain", "none", "initial", "inherit"],
  padding: ["length", "%", "initial", "inherit"],
  "padding-block": ["auto", "length", "%", "initial", "inherit"],
  "padding-block-end": ["auto", "length", "%", "initial", "inherit"],
  "padding-block-start": ["auto", "length", "%", "initial", "inherit"],
  "padding-bottom": ["length", "%", "initial", "inherit"],
  "padding-inline": ["auto", "length", "%", "initial", "inherit"],
  "padding-inline-end": ["auto", "length", "%", "initial", "inherit"],
  "padding-inline-start": ["auto", "length", "%", "initial", "inherit"],
  "padding-left": ["length", "%", "initial", "inherit"],
  "padding-right": ["length", "%", "initial", "inherit"],
  "padding-top": ["length", "%", "initial", "inherit"],
  "page-break-after": [
    "auto",
    "always",
    "avoid",
    "left",
    "right",
    "initial",
    "inherit",
  ],
  "page-break-before": [
    "auto",
    "always",
    "avoid",
    "left",
    "right",
    "initial",
    "inherit",
  ],
  "page-break-inside": ["auto", "avoid", "initial", "inherit"],
  "paint-order": [
    "normal",
    "one value",
    "two values",
    "three values",
    "initial",
    "inherit",
  ],
  perspective: ["length", "none", "initial", "inherit"],
  "perspective-origin": ["x-axis", "y-axis", "initial", "inherit"],
  "place-content": [
    "normal",
    "stretch",
    "start",
    "end",
    "center",
    "space-between",
    "space-around",
    "space-evenly",
    "overflow-alignment",
    "initial",
    "inherit",
  ],
  "place-items": [
    "normal legacy",
    "baseline",
    "center",
    "end",
    "start",
    "stretch",
    "initial",
    "inherit",
  ],
  "place-self": [
    "auto",
    "normal",
    "stretch",
    "start",
    "left",
    "center",
    "end",
    "right",
    "overflow-alignment",
    "baseline alignment",
    "initial",
    "inherit",
  ],
  "pointer-events": ["auto", "none", "initial", "inherit"],
  position: [
    "static",
    "absolute",
    "fixed",
    "relative",
    "sticky",
    "initial",
    "inherit",
  ],
  quotes: [
    "none",
    "string string string string",
    "initial",
    "inherit",
    '"',
    "'",
    "‹",
    "›",
    "«",
    "»",
    "‘",
    "’",
    "“",
    "”",
    "„",
  ],
  resize: ["none", "both", "horizontal", "vertical", "initial", "inherit"],
  right: ["auto", "length", "%", "initial", "inherit"],
  rotate: ["axis", "angle", "vector angle", "initial", "inherit"],
  "row-gap": ["length", "normal", "initial", "inherit"],
  scale: ["x-axis", "y-axis", "z-axis", "initial", "inherit"],
  "scroll-behavior": ["auto", "smooth", "initial", "inherit"],
  "scroll-margin": ["0", "length", "initial", "inherit"],
  "scroll-margin-block": ["0", "length", "initial", "inherit"],
  "scroll-margin-block-end": ["0", "length", "initial", "inherit"],
  "scroll-margin-block-start": ["0", "length", "initial", "inherit"],
  "scroll-margin-bottom": ["0", "length", "initial", "inherit"],
  "scroll-margin-inline": ["0", "length", "initial", "inherit"],
  "scroll-margin-inline-end": ["0", "length", "initial", "inherit"],
  "scroll-margin-inline-start": ["0", "length", "initial", "inherit"],
  "scroll-margin-left": ["0", "length", "initial", "inherit"],
  "scroll-margin-right": ["0", "length", "initial", "inherit"],
  "scroll-margin-top": ["0", "length", "initial", "inherit"],
  "scroll-padding": ["0", "length", "initial", "inherit"],
  "scroll-padding-block": ["0", "length", "initial", "inherit"],
  "scroll-padding-block-end": ["0", "length", "initial", "inherit"],
  "scroll-padding-block-start": ["0", "length", "initial", "inherit"],
  "scroll-padding-bottom": ["0", "length", "initial", "inherit"],
  "scroll-padding-inline": ["0", "length", "initial", "inherit"],
  "scroll-padding-inline-end": ["0", "length", "initial", "inherit"],
  "scroll-padding-inline-start": ["0", "length", "initial", "inherit"],
  "scroll-padding-left": ["0", "length", "initial", "inherit"],
  "scroll-padding-right": ["0", "length", "initial", "inherit"],
  "scroll-padding-top": ["0", "length", "initial", "inherit"],
  "scroll-snap-align": [
    "none",
    "start",
    "end",
    "center",
    "block inline",
    "initial",
    "inherit",
  ],
  "scroll-snap-stop": ["normal", "always", "initial", "inherit"],
  "scroll-snap-type": [
    "none",
    "x",
    "y",
    "block",
    "inline",
    "both",
    "mandatory",
    "proximity",
    "initial",
    "inherit",
  ],
  "scrollbar-color": ["auto", "color color", "initial", "inherit"],
  "tab-size": ["number", "length", "initial", "inherit"],
  "table-layout": ["auto", "fixed", "initial", "inherit"],
  "text-align": ["left", "right", "center", "justify", "initial", "inherit"],
  "text-align-last": [
    "auto",
    "left",
    "right",
    "center",
    "justify",
    "start",
    "end",
    "initial",
    "inherit",
  ],
  "text-decoration": [
    "text-decoration-line",
    "text-decoration-color",
    "text-decoration-style",
    "text-decoration-thickness",
    "initial",
    "inherit",
  ],
  "text-decoration-color": ["color", "initial", "inherit"],
  "text-decoration-line": [
    "none",
    "underline",
    "overline",
    "line-through",
    "initial",
    "inherit",
  ],
  "text-decoration-style": [
    "solid",
    "double",
    "dotted",
    "dashed",
    "wavy",
    "initial",
    "inherit",
  ],
  "text-decoration-thickness": [
    "auto",
    "from-font",
    "length/percentage",
    "initial",
    "inherit",
  ],
  "text-emphasis": [
    "none",
    "filled",
    "open",
    "dot",
    "circle",
    "double-circle",
    "triangle",
    "sesame",
    "string",
    "color",
    "initial",
    "inherit",
  ],
  "text-emphasis-color": ["color", "initial", "inherit"],
  "text-emphasis-position": [
    "over",
    "under",
    "left",
    "right",
    "initial",
    "inherit",
  ],
  "text-emphasis-style": [
    "none",
    "filled",
    "open",
    "dot",
    "circle",
    "double-circle",
    "triangle",
    "sesame",
    "string",
    "initial",
    "inherit",
  ],
  "text-indent": ["length", "%", "initial", "inherit"],
  "text-justify": [
    "auto",
    "inter-word",
    "inter-character",
    "none",
    "initial",
    "inherit",
  ],
  "text-orientation": [
    "mixed",
    "upright",
    "sideways",
    "sideways-right",
    "use-glyph-orientation",
    "initial",
    "inherit",
  ],
  "text-overflow": ["clip", "ellipsis", "string", "initial", "inherit"],
  "text-shadow": [
    "h-shadow",
    "v-shadow",
    "blur-radius",
    "color",
    "none",
    "initial",
    "inherit",
  ],
  "text-transform": [
    "none",
    "capitalize",
    "uppercase",
    "lowercase",
    "initial",
    "inherit",
  ],
  "text-underline-offset": [
    "auto",
    "length",
    "percentage",
    "initial",
    "inherit",
  ],
  "text-underline-position": [
    "auto",
    "under",
    "from-font",
    "left",
    "right",
    "initial",
    "inherit",
  ],
  top: ["auto", "length", "%", "initial", "inherit"],
  transform: [
    "none",
    "matrix(n,n,n,n,n,n)",
    "matrix3d(n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n)",
    "translate(x,y)",
    "translate3d(x,y,z)",
    "translateX(x)",
    "translateY(y)",
    "translateZ(z)",
    "scale(x,y)",
    "scale3d(x,y,z)",
    "scaleX(x)",
    "scaleY(y)",
    "scaleZ(z)",
    "rotate(angle)",
    "rotate3d(x,y,z,angle)",
    "rotateX(angle)",
    "rotateY(angle)",
    "rotateZ(angle)",
    "skew(x-angle,y-angle)",
    "skewX(angle)",
    "skewY(angle)",
    "perspective(n)",
    "initial",
    "inherit",
  ],
  "transform-origin": ["x-axis", "y-axis", "z-axis", "initial", "inherit"],
  "transform-style": ["flat", "preserve-3d", "initial", "inherit"],
  transition: [
    "transition-property",
    "transition-duration",
    "transition-timing-function",
    "transition-delay",
    "initial",
    "inherit",
  ],
  "transition-delay": ["time", "initial", "inherit"],
  "transition-duration": ["time", "initial", "inherit"],
  "transition-property": ["none", "all", "property", "initial", "inherit"],
  "transition-timing-function": [
    "ease",
    "linear",
    "ease-in",
    "ease-out",
    "ease-in-out",
    "step-start",
    "step-end",
    "steps(int,start|end)",
    "cubic-bezier(n,n,n,n)",
    "initial",
    "inherit",
  ],
  translate: ["x-axis", "y-axis", "z-axis", "initial", "inherit"],
  "unicode-bidi": [
    "normal",
    "embed",
    "bidi-override",
    "isolate",
    "isolate-override",
    "plaintext",
    "initial",
    "inherit",
  ],
  "user-select": ["auto", "none", "text", "all"],
  "vertical-align": [
    "baseline",
    "length",
    "%",
    "sub",
    "super",
    "top",
    "text-top",
    "middle",
    "bottom",
    "text-bottom",
    "initial",
    "inherit",
  ],
  visibility: ["visible", "hidden", "collapse", "initial", "inherit"],
  "white-space": [
    "normal",
    "nowrap",
    "pre",
    "pre-line",
    "pre-wrap",
    "initial",
    "inherit",
  ],
  widows: ["integer", "initial", "inherit"],
  width: ["auto", "length", "%", "initial", "inherit"],
  "word-break": [
    "normal",
    "break-all",
    "keep-all ",
    "break-word",
    "initial",
    "inherit",
  ],
  "word-spacing": ["normal", "length", "initial", "inherit"],
  "word-wrap": ["normal", "break-word", "initial", "inherit"],
  "writing-mode": ["horizontal-tb", "vertical-rl", "vertical-lr"],
  "z-index": ["auto", "number", "initial", "inherit"],
};
